# NUMPY

NumPy is a Python library used for working with arrays.

### Why Numpy when List in Python?

Fast: because how list stores data is: it stores the pointer to the object & which can be scattered in memory
While NumPy arrays are stored in a contiguous block of memory, meaning the elements are stored one after the other.

- Numpy stores in contiguos block of memory, List store pointer to the object which can be scattered in memory. **lagatar vako jhikna sajilo ki khojdai **
- Vectorized Operations on Numpy : no need for explicit loops
- NumPy functions are implemented in low-level languages like C and Fortran, which are compiled and highly optimized for performance. 

In [1]:
# importing library
import numpy as np

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Zeros array
zeros_arr = np.zeros((3, 4))

# Ones array
ones_arr = np.ones((2, 3))

# Identity matrix
identity_mat = np.eye(3)

# Range of values
range_arr = np.arange(0, 10, 2)

# Random array
random_arr = np.random.rand(3, 3)

In [11]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arithmetic Operations

In [7]:
arr_a = np.array([1, 2, 3 ])
arr_b = np.array([4, 5, 6])

# Element-wise addition
result_addition = arr_a + arr_b

# Element-wise multiplication
result_multiply = arr_a * arr_b

In [15]:
result_addition

array([5, 7, 9])

In [16]:
result_multiply

array([ 4, 10, 18])

## Matrix Operations

In [17]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result_matrix_multiply = np.dot(matrix_a, matrix_b)

In [18]:
result_matrix_multiply

array([[19, 22],
       [43, 50]])

In [57]:
result_matrix_multiply[0][0]=26
result_matrix_multiply

array([[26, 22],
       [43, 50]])

## Indexing & Slicing

In [19]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(arr[2])  # Output: 3

# Slicing
print(arr[1:4])  # Output: [2, 3, 4]

print(arr[1:]) 

print(arr[-1]) 

3
[2 3 4]
[2 3 4 5]
5


## Statistical Operations

In [20]:
arr = np.array([1, 2, 3, 4, 5])

# Mean, median, and standard deviation
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev = np.std(arr)

In [21]:
# works for normal distributions
mean_val

3.0

In [22]:
# best for skewed distributions not normal distributions
median_val

3.0

In [23]:
# a measure of how dispersed the data is in relation to the mean
std_dev

1.4142135623730951

## Array Reshaping

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape of the array
print(arr.shape)  # Output: (2, 3)

# Reshape the array
reshaped_arr = arr.reshape(3, 2)

(2, 3)


In [25]:
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
arr = np.arange(1,26).reshape(5,5)

In [63]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [81]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
arr[2,2]

13

In [87]:
val = np.arange(1,5).reshape(2,2)

In [88]:
val

array([[1, 2],
       [3, 4]])

In [89]:
val.sum()

10

## Universal Functions

In [26]:
arr = np.array([1, 2, 3, 4, 5])

# Element-wise square root
sqrt_arr = np.sqrt(arr)

# Element-wise sine
sin_arr = np.sin(arr)

In [27]:
sqrt_arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [28]:
import time

# Using NumPy arrays
start_time = time.time()
numpy_array = np.arange(10**6)
numpy_array = numpy_array ** 2
end_time = time.time()
print("NumPy time:", end_time - start_time)

# Using Python lists
start_time = time.time()
python_list = list(range(10**6))
python_list = [x**2 for x in python_list]
end_time = time.time()
print("Python list time:", end_time - start_time)

NumPy time: 0.02022075653076172
Python list time: 0.30379748344421387


## DEEP VS SHALLOW COPY

In [48]:
original_array = np.array([1, 2, 3])
shallow_copy = original_array

In [49]:
shallow_copy[0] = 10

In [50]:
shallow_copy

array([10,  2,  3])

In [51]:
original_array

array([10,  2,  3])

In [52]:
o_array = np.array([1, 2, 3])
deep_copy = np.copy(o_array)

In [53]:
deep_copy[0] = 100

In [54]:
deep_copy

array([100,   2,   3])

In [55]:
o_array

array([1, 2, 3])

## RANDOM

In [60]:
np.random.randn(3)

array([ 0.71179507, -1.49150226, -2.6991452 ])

## BROADCASTING

perform operations on arrays that may not have the same shape, as long as their dimensions are compatible

In [91]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([10, 20, 30])

result1 = arr2 + arr3
print(result1)

[[11 22 33]
 [14 25 36]]


In [92]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([10, 20])

In [94]:
result1 = arr2 + arr3
print(result1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [2]:
import numpy as np

In [3]:
t = np.arange(0., 5., 0.2)
t

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])