In [1]:
def print_args(*args):

    for arg in args:
        print(arg)

In [2]:
print_args(1)

1


In [3]:
print_args(1,'yay')

1
yay


In [8]:
def print_kwargs(**kw):
    for key,value in kw.items():
        print(f"{key}:{value}")
        

In [14]:
print_kwargs(name="jon",age=25)

name:jon
age:25


In [13]:
with open('data.txt','r') as file:
    content =file.read()
    print(content)


i am shital


In [15]:
def subval(x,y):
    return x-y
res =subval(1,2)
print(res)

-1


In [19]:
result=lambda x,y:x-y

In [20]:
res=result(4,2)

In [21]:
res

2

# REGULAR EXPRESSIONS


In [30]:
import re
text ="shital was born in 2000-06-18"

In [31]:
pattern =r'\d{4}-\d{2}-\d{2}'

In [32]:
match =re.search(pattern,text)

if match:
    print(f"FOUND {match.group()}")



FOUND 2000-06-18


# NUMPY

In [1]:
import numpy as np

In [2]:
arr_1d =np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [3]:
arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
zeros_arr=np.zeros((3,3))

In [5]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones_arr=np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
identity_mat= np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ARTHMETIC operation  in numpy

In [10]:
array_a=np.array([2,3,4])
array_b=np.array([5,6,7])

In [11]:
res_add=array_a+array_b
res_mul=array_a*array_b

In [12]:
res_add

array([ 7,  9, 11])

In [13]:
res_mul

array([10, 18, 28])

# MATRIX OPERATION

In [14]:
mat_a=np.array([[1,2],[3,4]])
mat_b=np.array([[3,4],[9,8]])

In [15]:
result_mat=np.dot(mat_a,mat_b)
result_mat

array([[21, 20],
       [45, 44]])

In [16]:
result_mat[1][1]

44

In [17]:
result_mat

array([[21, 20],
       [45, 44]])

In [18]:
result_mat[0][0]=45

In [19]:
result_mat

array([[45, 20],
       [45, 44]])

# indexing & slicing

In [20]:
arr=np.array([1,2,3,4,6])

In [21]:
print(arr[2])

3


In [22]:
print(arr[-1])

6


In [23]:
print(arr[1:])

[2 3 4 6]


In [24]:
print(arr[:-2])

[1 2 3]


 # STATISTICAL OPERATION

In [25]:
arr=np.array([1,2,3,4,5])

In [26]:
mean_val=np.mean(arr)

In [27]:
mean_val

3.0

In [28]:
median_val=np.median(arr)

In [29]:
median_val

3.0

In [30]:
std_dev=np.std(arr)

In [31]:
std_dev

1.4142135623730951

# ARRAY RESHAPE

In [33]:
arr=np.array([[1,2,3],[4,5,6]])

In [34]:
arr.shape

(2, 3)

In [35]:
reshaoed_arr =arr.reshape(3,2)

In [36]:
reshaoed_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
arr=np.arange(1,26)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [56]:
import time
#py list
start_time=time.time()
python_list=list(range(10**6))
python_list=[x**2 for x in python_list]
end_time=time.time()
print("python list execution time",end_time-start_time)
 #numpy list
start_time=time.time()
numpy_array=np.arange(10**6)
numpy_array=numpy_array**2
end_time=time.time()
print("PYTHON NUMPY EXECUTION TIME",end_time-start_time)

      

      

python list execution time 0.18137860298156738
PYTHON NUMPY EXECUTION TIME 0.008025646209716797


# deep vs shallow copy

In [45]:
original_array=np.array([1,2,3])

In [46]:
shallow_copy=original_array

In [47]:
shallow_copy[0]=10

In [48]:
shallow_copy

array([10,  2,  3])

In [49]:
original_array

array([10,  2,  3])

In [50]:
original_array=np.array([1,2,3])

In [51]:
deep_copy=np.copy(original_array)

In [52]:
deep_copy[0]=10

In [53]:
deep_copy

array([10,  2,  3])

In [54]:
original_array

array([1, 2, 3])

In [55]:
np.random.randn(1)[0]

-0.10729424350987884

# pandas
data munipulation &Anal

In [9]:
import pandas as pd


C:\Users\Acer\AppData\Local\Temp\ipykernel_14176\2035458946.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [5]:
s=pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
data={
    'name':['shital','sandy','sujan'],
    'age':[20,21,22],
    'city':['ktm','brt','pkr']
}
df=pd.DataFrame(data)
df

name  age city
0  shital   20  ktm
1   sandy   21  brt
2   sujan   22  pkr

In [7]:
lables=['a','b','c']

In [11]:
ser1=pd.Series([1,2,3],['a','b','c'])

In [12]:
ser1

a    1
b    2
c    3
dtype: int64

In [15]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [16]:
df

W         X         Y         Z
A -0.015362  0.552017  1.907523  0.197001
B  0.411889  0.015654  0.897207  0.512242
C -0.109468  0.568126 -0.105738  0.843123
D -0.597893 -1.234413  0.703033 -0.995469
E -0.855002 -1.353132 -0.246187 -0.278827

In [17]:
df["W"]

A   -0.015362
B    0.411889
C   -0.109468
D   -0.597893
E   -0.855002
Name: W, dtype: float64

In [18]:
df[["W","Z"]]

W         Z
A -0.015362  0.197001
B  0.411889  0.512242
C -0.109468  0.843123
D -0.597893 -0.995469
E -0.855002 -0.278827

In [19]:
df.loc['A']

W   -0.015362
X    0.552017
Y    1.907523
Z    0.197001
Name: A, dtype: float64

In [20]:
df.iloc[0]


W   -0.015362
X    0.552017
Y    1.907523
Z    0.197001
Name: A, dtype: float64

In [21]:
df['W'].loc['A']

-0.015362242402199711

In [22]:
df['W'].loc[['C','D']]

C   -0.109468
D   -0.597893
Name: W, dtype: float64

In [23]:
df

W         X         Y         Z
A -0.015362  0.552017  1.907523  0.197001
B  0.411889  0.015654  0.897207  0.512242
C -0.109468  0.568126 -0.105738  0.843123
D -0.597893 -1.234413  0.703033 -0.995469
E -0.855002 -1.353132 -0.246187 -0.278827

In [24]:
df['new']=df['W']+df['Z']

In [25]:
df

W         X         Y         Z       new
A -0.015362  0.552017  1.907523  0.197001  0.181638
B  0.411889  0.015654  0.897207  0.512242  0.924131
C -0.109468  0.568126 -0.105738  0.843123  0.733654
D -0.597893 -1.234413  0.703033 -0.995469 -1.593362
E -0.855002 -1.353132 -0.246187 -0.278827 -1.133829

In [29]:
def times2(x):
   return x*2

In [31]:
df["W"].apply(lambda x:x*2)

A   -0.030724
B    0.823779
C   -0.218936
D   -1.195786
E   -1.710005
Name: W, dtype: float64

In [34]:
df.drop('new',axis=1,inplace=True)

In [33]:
df.drop('E',axis=0)

W         X         Y         Z       new
A -0.015362  0.552017  1.907523  0.197001  0.181638
B  0.411889  0.015654  0.897207  0.512242  0.924131
C -0.109468  0.568126 -0.105738  0.843123  0.733654
D -0.597893 -1.234413  0.703033 -0.995469 -1.593362

In [35]:
df>0

W      X      Y      Z
A  False   True   True   True
B   True   True   True   True
C  False   True  False   True
D  False  False   True  False
E  False  False  False  False

In [36]:
df>1

W      X      Y      Z
A  False  False   True  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False  False  False

# MISSING DATA

In [41]:
d={'A':[1,np.nan,3],'B':[4,5,6]}
data=pd.DataFrame(d)

In [42]:
data

A  B
0  1.0  4
1  NaN  5
2  3.0  6

In [43]:
data.dropna(axis=1)

B
0  4
1  5
2  6

In [44]:
data.dropna(axis=1,thresh=2)

A  B
0  1.0  4
1  NaN  5
2  3.0  6

In [3]:
d={
    'company':['ABC','DEF','BCD'],
    'sales':[4000,5000,6000],
    'product':['SAAS','BAAS','service']
}

In [10]:
df = pd.DataFrame(d)

In [11]:
df

company  sales  product
0     ABC   4000     SAAS
1     DEF   5000     BAAS
2     BCD   6000  service

In [17]:
bycomp=df.groupby("company")
bycomp.sum()

sales  product
company                
ABC       4000     SAAS
BCD       6000  service
DEF       5000     BAAS

## DESCRIBE

In [19]:
df.describe()

sales
count     3.0
mean   5000.0
std    1000.0
min    4000.0
25%    4500.0
50%    5000.0
75%    5500.0
max    6000.0

## CONCATENTATION
pd.concat([a,b])
dimension has to match

In [48]:
df1=pd.DataFrame({
    'A':[1,2,3],
    'B':[4,5,6],
    'key':[7,6,5]
},index=[1,2,3])

In [49]:
df2=pd.DataFrame({
    'C':['a','b','c'],
    'D':['s','f','g'],
    'key':[7,8,9]
},index=[1,5,6])

In [50]:
concat_data=pd.concat([df1,df2],axis=1)
concat_data

A    B  key    C    D  key
1  1.0  4.0  7.0    a    s  7.0
2  2.0  5.0  6.0  NaN  NaN  NaN
3  3.0  6.0  5.0  NaN  NaN  NaN
5  NaN  NaN  NaN    b    f  8.0
6  NaN  NaN  NaN    c    g  9.0

# MERGE

In [51]:
df1

A  B  key
1  1  4    7
2  2  5    6
3  3  6    5

In [52]:
df2

C  D  key
1  a  s    7
5  b  f    8
6  c  g    9

In [53]:
pd.merge(df1,df2,how="left",on="key")

A  B  key    C    D
0  1  4    7    a    s
1  2  5    6  NaN  NaN
2  3  6    5  NaN  NaN

In [54]:
pd.merge(df1,df2,how="inner",on="key")

A  B  key  C  D
0  1  4    7  a  s

In [55]:
pd.merge(df1,df2,how="outer",on="key")

A    B  key    C    D
0  3.0  6.0    5  NaN  NaN
1  2.0  5.0    6  NaN  NaN
2  1.0  4.0    7    a    s
3  NaN  NaN    8    b    f
4  NaN  NaN    9    c    g

In [56]:
pd.merge(df1,df2,how="right",on="key")

A    B  key  C  D
0  1.0  4.0    7  a  s
1  NaN  NaN    8  b  f
2  NaN  NaN    9  c  g

In [59]:
jjoindata=df1.join(df2,how='right')
jjoindata

ValueError: columns overlap but no suffix specified: Index(['key'], dtype='object')

In [61]:
d={
    'categories':['abc','dfg','hjk'],
    'Product':['noodle','software','system']
}




In [63]:
df=pd.DataFrame(d)

In [64]:
df

categories   Product
0        abc    noodle
1        dfg  software
2        hjk    system

In [6]:
import pandas as pd


C:\Users\Acer\AppData\Local\Temp\ipykernel_24812\2035458946.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [13]:
data=pd.read_csv("example.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'example.csv'

In [8]:
d={
    'company':['ABC','DEF','BCD'],
    'sales':[4000,5000,6000],
    'product':['SAAS','BAAS','service']
}
df=pd.DataFrame(d)
df.to_csv("data_val.csv")

# PRACTICE DATAFRAME

In [15]:
sal=pd.read_csv("salaries.csv")

In [16]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [18]:
sal.head(2)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN

In [19]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [20]:
sal['BasePay']

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...    
148649         0.00
148650          NaN
148651          NaN
148652          NaN
148653         0.00
Name: BasePay, Length: 148654, dtype: float64

In [21]:
sal['BasePay'].mean()

66325.4488404877

In [22]:
sal['BasePay'].max()

319275.01

In [23]:
sal['OvertimePay'].max()

245131.88

# GARY JIMENEZ ,job title

In [24]:
sal['EmployeeName']=='GARY JIMENEZ'

0         False
1          True
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

In [25]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [26]:
sal[sal['EmployeeName']=='GARY JIMENEZ']

Id  EmployeeName                         JobTitle    BasePay  OvertimePay  \
1   2  GARY JIMENEZ  CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
1  137811.38       NaN  538909.28         538909.28  2011    NaN   

          Agency  Status  
1  San Francisco     NaN

In [27]:
sal[sal['EmployeeName']=='GARY JIMENEZ']['JobTitle']

1    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

# highest paid person

In [32]:
sal['TotalPay'].max()

567595.43

In [33]:
sal['TotalPay']==sal['TotalPay'].max()

0          True
1         False
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: TotalPay, Length: 148654, dtype: bool

In [34]:
sal[sal['TotalPay']==sal['TotalPay'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [35]:
sal.head(1)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [36]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [40]:
sal['year']==2011

0         True
1         True
2         True
3         True
4         True
          ... 
148649    True
148650    True
148651    True
148652    True
148653    True
Name: year, Length: 148654, dtype: bool

In [41]:
sal[sal['year']==2011]['TotalPay'].mean()

74768.32197169267

In [52]:
sal['year']==2012

0         False
1         False
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: year, Length: 148654, dtype: bool

In [53]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  year  
0         NaN  San Francisco     NaN  2011  
1         NaN  San Francisco     NaN  2011  
2         NaN  San Francisco     NaN  2011  
3         NaN  San Francisco     NaN  2011  
4         NaN  San Francisco     NaN  2011  
...       ...            ...     ...   ...  
148649    NaN  San Francisco     NaN  2011  
148650    NaN  San Francisco     NaN  2011  
148651    NaN  San Francisco     NaN  2011  
148652    NaN  San Francisco     NaN  2011  
148653    NaN  San Francisco     NaN  2011  

[148654 rows x 14 columns]

In [54]:
data=sal[['year','BasePay']]

In [55]:
data

year    BasePay
0       2011  167411.18
1       2011  155966.02
2       2011  212739.13
3       2011   77916.00
4       2011  134401.60
...      ...        ...
148649  2011       0.00
148650  2011        NaN
148651  2011        NaN
148652  2011        NaN
148653  2011       0.00

[148654 rows x 2 columns]

In [56]:
data.groupby('year').mean()['BasePay']

year
2011    66325.44884
Name: BasePay, dtype: float64

In [57]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [58]:
sal['JobTitle'].nunique()

2159

In [59]:
sal['JobTitle']==2013

0         False
1         False
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [65]:
sal[sal['Year']==2013]['JobTitle'].value_counts()==1

JobTitle
Transit Operator                  False
Special Nurse                     False
Registered Nurse                  False
Public Svc Aide-Public Works      False
Custodian                         False
                                  ...  
Sr General Utility Mechanic        True
Sprv Adult Prob Ofc (SFERS)        True
Mayoral Staff XII                  True
Pr Investigator, Tax Collector     True
Senior Assessment Clerk            True
Name: count, Length: 1051, dtype: bool

In [66]:
sal[sal['Year']==2013]['JobTitle'].value_counts()

JobTitle
Transit Operator                  2295
Special Nurse                     1445
Registered Nurse                  1231
Public Svc Aide-Public Works       859
Custodian                          789
                                  ... 
Sr General Utility Mechanic          1
Sprv Adult Prob Ofc (SFERS)          1
Mayoral Staff XII                    1
Pr Investigator, Tax Collector       1
Senior Assessment Clerk              1
Name: count, Length: 1051, dtype: int64

In [67]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [74]:
def chief_string(text):
    if'chief' in text.lower():
        return True
    else:
        return False

In [75]:
sum(sal['JobTitle'].apply(chief_string))

627

In [78]:
sal[sal["JobTitle"].str.contains("chief")]["JobTitle"]

Series([], Name: JobTitle, dtype: object)